### ISSUE TITLE
display creata date / modify date

### ISSUE THREAD

**Issue by bomhard** [gturri/nspages#104]
Hi,

it would be great if the list would contain the modify date or create date respectively when sorted by them. 

Best
Nikolaus

**Comment by gturri** [comment]
It's an interesting idea, especially given that the `-usePictures` mode already supports this (with the `-modificationDateOnPictures` option)

I think that, in order to avoid changing existing behavior, this should be done through an new option (for instance `-displayModificationDate`).

I think it shouldn't be too hard to do. However, I'm afraid I may not be able to do it any time soon. But I could give pointers to someone willing to do a pull request.

**Comment by gturri** [comment]
I've just spent some time on it. It's still work in progress, but you can already give it a try @bomhard 
Just:
- download the updated plugin at https://github.com/gturri/nspages/archive/dev_104.zip and install it
- add the option `-modificationDateOnPictures`

Don't hesitate to let me know if it's the kind of stuff you were looking for.

**Comment by gturri** [comment]
This option has been added in version 2020-07-09 of the plugin
