### ISSUE TITLE
-pagesInNs breaks ordering of parent namespaces

### ISSUE THREAD

**Issue by Phoenix616** [gturri/nspages#109]
When using tree mode then the parent elements seem to not be ordered in their natural order.

Here is an example: `<nspages -tree -r=2 -subns -pagesInNs -h1 -textNs="" -exclude:[start wiki: playground:]>` results in the following tree:

![](https://i.minecraft.ceo/fOYPAb6l.png)

As one can tell, "RandomTeleport" comes before "ConnectorPlugin" even though that's not correct.

Some testing has shown that this is caused by the `-pagesInNs` option. When removing that option it will correctly move "RandomTeleport" below the other entry and not dispaly any sub-pages of the "RandomTeleport" element ("ConnectorPlugin" has a sub-namespaces so it would still shown)

---

What might also be interesting: When setting `-r=1` it will result in the expected order, probably because it doesn't have to deal with sub pages/namespaces:

![](https://i.moep.tv/fLKphFeC.png)

**Comment by gturri** [comment]
Thanks for the bug report. Indeed it appears that building the tree doesn't preserve the order for namespaces.

The fix would be to sort each node after the tree is built. The small difficulty is to be able to apply the sorting logic (wrt the flags which can be passed) , which require a small refactoring preliminary work.

I just took a moment to give it a try (https://github.com/gturri/nspages/commit/bc28736e57ffa2ccb0766ce2e5061a322017480a ) but more work is needed (in particular because this commit is breaking stuff).
TBH I'm not sure I'll be able to take the time to work on it in the next few weeks. (OTHO I would gladly have a look at PR).

**Comment by gturri** [comment]
Actually I managed to fix it. It should be all good if you update to the latest version of the plugin (2020-11-25)

**Comment by Phoenix616** [comment]
Works like a charm. Thank you!
