### ISSUE TITLE
Duplicated entries

### ISSUE THREAD

**Issue by philippemilink** [gturri/nspages#114]
Hello,

Thanks for this plugin, it has all the features I was looking for. However, I think I found a bug: some entries are duplicated.

To reproduce:
1. install the last version of dokuwiki
2. install the nspages plugin
3. create / edit the start page and add the following content: 
```
====== Start page ======

<nspages -r -exclude:user: -exclude:wiki: -exclude:playground: -subns -pagesInNs -h1 -textNS="">
```
4. create the page `foo:start` with the following content:
```
====== Foo ======

Foo
```
5. Go back to the start page: the `Foo`entry appears twice.

I had a look in the code, and if I change [this line](https://github.com/gturri/nspages/blob/master/syntax.php#L148) into this one:
```php
$subnamespaces = $pages;
```
(use only `$pages` instead of `$subnamespaces` _and_ `$pages`) the duplication disappears.

Is there a missing configuration key here to set this behaviour, or _am I_ missing a configuration key ?

**Comment by gturri** [comment]
Thank you for this bug report.

This behavior is a consequence of the flag `-pagesInNs`: you have a `Foo` which represents the namespace `foo:` and another one which represents the page `foo:start`. It might be clearer if you remove the flag `-h1` because then both entries will have different name.

That's the point of the line `$subnamespaces = array_merge($subnamespaces, $pages);`: it is ran because the flag `-pagesInNs` is set (that's what the `if` [on the line above ](https://github.com/gturri/nspages/blob/master/syntax.php#L147)checks). Replacing this line with `$subnamespaces = $pages;` would  hence have the same effect as remove both flags `-subns` and `-pagesInNs`.

Does that make sense?

**Comment by philippemilink** [comment]
Thank you for your answer, removing flags `-subns` and `-pagesInNs` did the trick.

I read again the plugin documentation, and I realized the `-r` flag is sufficient to display all pages (with `-h1` to make things clearer !). When I read it the first time, I understood this flag as "browse recursively _namespaces_ but do not display pages", I thought `pagesInNs` was mandatory to display pages of namespaces. Oh, I now read it a third time and I finally get `-r` displays only leafs of page tree, not internal nodes (which are namespaces), which is what I was looking for ! (Maybe you can clarify this point in the documentation ?)

**Comment by gturri** [comment]
Thanks for the suggestion. I just updated the doc. I hope it's less ambiguous now.
