### ISSUE TITLE
Images Not Showing Up with -usePictures option

### ISSUE THREAD

**Issue by cuttherug** [gturri/nspages#121]
For some reason my list just show a blank square behind the text.

Here is the code I'm using in the image below.

Thank you for any help!

![nspages picture issue - Copy](https://user-images.githubusercontent.com/3887315/163699747-6283e87f-8f08-489a-8b57-91cb67486f46.png)

**Comment by gturri** [comment]
I'm afraid I don't have enough information to understand what is going on.

Could you right click on a place where an image should be and select "Inspect" (or something like this, depending on the browser you are using and its language) and show me the line that matches the div with class class="nspagesPicturesModeImg" (like this
![image](https://user-images.githubusercontent.com/308601/163703927-c4cbb83e-9668-4dff-83c5-6b639f185da2.png)
)

and then could you open the network panel of the dev tools of your browser, reload the page, and look how the load of the expected image went (as in my screenshot below 
![image](https://user-images.githubusercontent.com/308601/163703974-75b853b6-04ff-474b-9a1a-b8acd9b82b50.png)
)

**Comment by gturri** [comment]
Since your shared a link to your wiki in the other bug report I had a look directly.
It turns out that:
- dokuwiki does not seem to consider that your pages have images. I suspect it's related to the usage of the "wrap" plugin. So nspages should try to fallback to the logo of your wiki, but it can't find it 
![image](https://user-images.githubusercontent.com/308601/163704087-8f9037e5-2a67-452d-93fa-a211f6ea15c2.png)


You could try this workaround:  include a 1×1 pixel size image as the 1st picture your pages: that way they won't be visible on those pages but they would be picked by nspages.

**Comment by cuttherug** [comment]
Thank you I was just about to say it looks like it's pointing to the wrong location.

I will try to post an image at the very top of the page, but I think I just did that and it didn't work.

**Comment by cuttherug** [comment]
For some reason it still doesn't seem to be working. Here is the chrono trigger page where I have placed an image at the very top before any other code https://definitiveversion.com/doku.php?id=video_games:chrono_trigger.

Also, I tried refreshing my cache and that didn't seem to do anything just in case that might be an issue.

Thank you again for the replies!

**Comment by gturri** [comment]
Your page https://definitiveversion.com/doku.php?id=code_testing is still trying to load the logo and I'm not sure why.
Could you look at the metadata of your page (it should be a file located at `data/meta/video_games/chrono_trigger.meta`) and tell the value associated with the key `firstimage`?

**Comment by cuttherug** [comment]
Here's the code surrounding first image

{s:10:"references";a:1:{s:15:"tag:video_games";b:0;}s:10:"firstimage";s:0:"";}s:8:"internal";a:2:{s:5:"cache";b:1;s:3:"toc";b:1;}s:11:"description";a:1:{s:8:"abstract";s:258:"CHRONO TRIGGER

it looks like the value is ";s:0:"?

**Comment by gturri** [comment]
Thanks.
Yes, the value is `s:0` which is the PHP serialized representation of an empty string. That's weird, I would have expected someting like `:chrono_trigger_-_box_art_snes_.png`. I'm not sure why it's not the case but at least it explains the behavior of nspages (because nspages relies on this metadata to find out the image to use).
I'm afraid there is not much I can do for you know since the question is now to understand why the metadata is not correctly filled, and since this is outside the scope of nspages (however when you find out what went on, please let me: it makes me curious)

nb: my previous intuitition that the wrap plugin could interefer, is probably wrong, since we have this behavior even when you don't use this plugin...

**Comment by cuttherug** [comment]
I'm guessing some sort of plugin is interfering with the meta data. 

Is there a way to manually  point to the image? Can I edit the .meta file?

**Comment by cuttherug** [comment]
I turned off this plugin today and now it's working.

https://github.com/lupo49/plugin-lightbox

**Comment by gturri** [comment]
Congratulations for finding the cause of the issue!
