### ISSUE TITLE
absolute path not working

### ISSUE THREAD

**Issue by froehlich-info** [gturri/nspages#124]
Hello Folks!

The path given to the plugin is always interpreted as relative. The paths .:namespace and namespace  produce the same output. 

I modified syntax.php on line 98. 
    $namespace .= trim ( $match );
no concat is needed, because the namespaceFinder class handles the ramainder of $match.

    $namespace = trim ( $match ); // removed the concatenator

and now it works. If this suggestion suits you and does not mess up other functionalities, please think about incorporating it into the next release. 

Great Plugin! I appreciate the work ^_^

Kindly, Frederic

IT-Lead at froehlich.ch

**Comment by froehlich-info** [comment]
of course, everytime the syntax has been ignored one has to change 
:ns 
to 
.:ns
, since the colon does default to absolute namespaces

I ran this cli command on GNU/linux dokuwiki base dir to fix this

find ./data/pages/ -type f -iname "*.txt" -exec sed -i 's/nspages :<your NS>/nspages .:<your NS>/g' {} \; 

Our wiki had a lot of nspages listings for generic directories.

Cheers!

**Comment by gturri** [comment]
Thanks for this feedback!

There is something I'm not sure I understand in the sentence `The path given to the plugin is always interpreted as relative` because, if I remember correctly, a patch which starts with `:` is supposed to be interpreted as an absolute path.
(So it's expected that `namespace` and `.:namespace` represent the same path, but `:namespace` should represent another one).

Don't hesitate to let me know if you think I misunderstood something in your explanation.

**Comment by froehlich-info** [comment]
Man, I am terribly sorry. I use a modified version... 

I did not check the integrity of my version. I compared it now and you are completely right. In my company for some it was hard to get the difference of   :ns    .:ns    and    ns    so  I hacked your plugin (-_-) and built in the "error".

My bad, your plugin is great and helpful!

Cheers anyhow, I am a little ashamed ^_^

Frederic
