### ISSUE TITLE
Conflict with plugin dropfiles

### ISSUE THREAD

**Issue by Drachenlaeufer** [gturri/nspages#158]
When dropfiles is installed, then nspages produces a tree of all pages of the whole wiki. Even when the plugin is deactived it shows this behavior. 

nspages: 2023-09-16
dropfiles: 2020-03-18
dokuwiki: 2023-04-04a

**Comment by gturri** [comment]
Thanks for this bug report!

I'm afraid I'm not able to reproduce that issue. What I tried:
- I installed the dropfiles plugin, removed the cache of my wiki, and displayed a page. But it was displayed as expected.
- Then I had a quick look at the dropfiles plugin code, but I don't see anything that could explain a conflicts.

Could you please give me more clues in order to reproduce that issue? For instance a detailed procedure step by step from a fresh dokuwiki instance that would reproduce that issue? (In particular it would be interesting to know how you invoke nspages (ie: with which arguments). It could also be helpful to get a screenshot of what you see with nspages before installing dropfiles, and and then after)

**Comment by Drachenlaeufer** [comment]
And I cannot reproduce it today, too. :-/
Yesterday that behavior was there, always. I could delete and reinstall both plugins, activate and deactivate them.
Now it's gone. And neither any other plugins, nor dokuwiki nor anything in the system changed. 
Really strange.
Sorry, but I would close this.
