### ISSUE TITLE
Return type of NspagesTreeNsNode::offsetXY() should either be compatible with AccessAccess::offsetXY [...]

### ISSUE THREAD

**Issue by fjf2002** [gturri/nspages#168]
I am currently running the indexer. The output gets spammed with:

> Return type of NspagesTreeNsNode::offsetXY() should either be compatible with AccessAccess::offsetXY or the #\[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

I am using PHP 8.0 .

Compare 
https://github.com/gturri/nspages/blob/61857ee52e02c1f42d8dcb540aa80ba411db1485/printers/printerTree.php

with https://www.php.net/manual/en/class.arrayaccess.php : Parameter types and return types are missing.

I suppose there is a trade-off with supporting old PHP versions without return type capabilities (?)

**Comment by gturri** [comment]
Thanks for this bug report!

I'm afraid I'm not able to see those warning on my side, I'm not sure why. Even though I'm running PHP 8.3.6 with `display_errors = On` and `error_reporting = E_ALL`.
Do you have any clues about what I could be missing?

(as far as supporting old PHP versions is concerned, I see on https://www.dokuwiki.org/popularity#php_version that more than 40% of dokuwiki instances are PHP 7 or older... but since those versions are not supported anymore for at least 2 years, I guess it's ok to not support it anymore here)

**Comment by gturri** [comment]
Btw, since it seems clear to you how it should be fixed, what about submitting a pull request?

**Comment by fjf2002** [comment]
> I'm afraid I'm not able to see those warning on my side, I'm not sure why

When I open a Dokuwiki page containing the 'nspages' tag in the browser, I get the warnings. - In my VSCode Debug console, NOT in the Dokuwiki debug log.

I am using PHP 8.2 .
