### ISSUE TITLE
Add option to set relation_references

### ISSUE THREAD

**Issue by d00p** [gturri/nspages#57]
It would be helpful for other plugins (e.g. backlinks2) if nspages could store the relation_references so the auto-generated links are being recognized. A new and optional parameter/option would be nice to enable/disable this behaviour.

**Comment by gturri** [comment]
Thank you for your bug report. It would indeed make sense to handle nicely relation_references.

Just to be sure I understand completely: it already works fine when the page is created or edited, but metadata aren't updated when pages displayed in the TOC are created / deleted.

More precisely: say I have the pages `sandbox:a` and `sandbox:b`. I then create then create the page `sandbox:start` with the content

    ~~NOCACHE~~ 
    <nspages -h1 -subns -exclude>

now the file `data/meta/sandbox/start.meta` contains `"references";a:2:{s:9:"sandbox:a";b:1;s:9:"sandbox:b";b:1;}`, which is fine.

But if I add the page `sandbox:c`, then the metadata isn't updated accordingly.

AFAIU, we're saying the in the case where the  `c` page is created, then the metadata should eventually been updated, without requiring to edit the `start` page.

Is my understanding correct, or are we talking about something else?

**Comment by gturri** [comment]
Actually I'm realizing that in dokuwiki's code there's a reference to a metadata literally called [relation_references ](http://xref.dokuwiki.org/reference/dokuwiki/nav.html?inc/indexer.php.source.html#l1418) (instead of a metadata called `references` as a key of the metadata `relation`).
On the other hand, when I grep in the `data/meta` directory of my server, I don't find any reference to `relation_references`, so I don't really understand how it's supposed to work, and I would be grateful if you can give me more information.

**Comment by d00p** [comment]
My (specific) need:

`sandbox` along with `sandbox:a`, `sandbox:b` and `sandbox:c`

Now: in `sandbox` there is `<nspages -h1 .:sandbox -simpleList -textPages="">`
And in the the subpages `a`, `b` and `c` there is `{{backlinks>.}}`

What I wanted/need is that `{{backlinks>.}}` shows a link to `sandbox` on the subpages but due to the lack of some kind of reference, it shows nothing, because `nspages``s listing is autogenerated

**Comment by gturri** [comment]
Thanks for this precision. 

So, AFAICS, as long as `sandbox:a` & Co are created before `<nspages -h1 .:sandbox -simpleList -textPages="">` is added in the main page, then it works fine (ie: there's indeed a backlink which points to the main page).
On the other hand, the required metadata (hence the backlink) is missing for pages which are created after that.

It means that a workaround would be to edit the main page (eg: adding a whitespace at the end) when a new subpage is created. It's cumbersome, but it would ensure proper backlinks.

I'll eventually try to improve it. But first I'll need to get a better understanding of how the indexer and its events work. And since I currently don't have a lot of free time, I will likely not be able to work on it soon.

**Comment by d00p** [comment]
Rebuilding/updating the (search)index also does the trick. Thanks for your info, think this works for me so far. Great support, thanks :+1:

**Comment by gturri** [comment]
Actually, I'm realizing that on a wiki where acl are enabled, this problematic is quite tricky, since nspages takes the permissions of the current user into account (in order to not display a link to a page the user cannot read).
So the notion of backlink should actually depend on the current user. But since it's read from cached metadata, it's not possible.

Long story short: nspages cannot handle correctly metadata. I'm hence closing the issue since I'm afraid there's nothing else to do.
