### ISSUE TITLE
Hide option for Subnamespaces

### ISSUE THREAD

**Issue by tofighi** [gturri/nspages#69]
If it is possible, add an option to hide the following titles on top of the list of namespaces and pages:

Subnamespaces:
Pages in this namespace:

**Comment by gturri** [comment]
It's already possible. See #67 for the title above the list of pages. The approach is similar for the list of namespaces (using `-textNS` instead of `-textPages`).

Since you're not the first one who is asking this, it means that the doc on https://www.dokuwiki.org/plugin:nspages can be improved. As a user who sees this doc with fresh eyes, I would be grateful if you can update it in a way that would have let you easily understand how this works.

**Comment by jgod** [comment]
I added a note to the docs since it's named confusingly (imo). I only found that I could change it by searching these GitHub issues.
