### ISSUE TITLE
More about -dictionaryOrder

### ISSUE THREAD

**Issue by bilo1967** [gturri/nspages#95]
Thank you for accepting my pull request.

It came to my mind that a complete dictionary sort by locale should also be a natural sort while the code I provided yesterday isn't. 

So I wrote the following _natcoll() compare function which could be used instead of strcoll() in `printers/printer.php`  Do you think it might be worth using it? 

```
<?php
function _natcoll($s1, $s2) {

    $l1 = preg_match_all('/([^0-9]+)|([0-9]+)/', $s1, $m1);
    $l2 = preg_match_all('/([^0-9]+)|([0-9]+)/', $s2, $m2);

    $result = 0;
    for ($i = 0; $i < max($l1, $l2); $i++) {
        if (!isset($m1[0][$i])) {
            $result = -1;
        } else if (!isset($m2[0][$i])) {
            $result = 1;
        } else if ($m1[1][$i] != "" && $m2[1][$i] != "") {
            $result = strcoll($m1[1][$i], $m2[1][$i]);
        } else if ($m1[2][$i] != "" && $m2[2][$i] != "") {
            $result = intval($m1[2][$i]) - intval($m2[2][$i]);
        } else if ($m1[0][$i] != $m2[0][$i]) {
            $result = strnatcmp($m1[0][$i], $m2[0][$i]);
        }
        if ($result) break;
    }

    return $result;
}

$locale = "it_IT.utf8";
$array = array("prova 4", "blood", "ético", "bacíle", "straziato", "calo", "Camera", "Canal", "Concatenacion", "bacillo", "Cliente", "prova 211", "Calò", "etico", "Strain", "strasse", "Concatenación", "Prova 31", "Cámara", "Calidad", "1", "913", "313", "", " ", "Straße", "pesca", "pésca", "pescare", "canál", "bacile", "blöd");

$oldLocale=setlocale(LC_ALL, 0);
setlocale(LC_COLLATE, $locale);
usort($array, '_natcoll');
setlocale(LC_COLLATE, $oldLocale);

echo "\nnatcoll\n";
print_r($array);
?>

```

**Comment by gturri** [comment]
I'm wondering whether this notion of having both natural and dictionary sort is perhaps a bit overkill.
In particular I'm not sure I understand how those notions should be mixed (I mean: dictionary order isn't compatible with natural order in the first place).
And I'm not really comfortable with implementing such an ad hoc sort function because my understanding is that if it fulfilled a standard need then it would be provided by PHP itself. ie : PHP provides `strcasecmp`, `strnatcasecmp` and `strcoll`. If it provides another sort function then it could be an idea to be able to plug nspages on it; otherwise I feel it would be like trying to implement something too exotic.
