### ISSUE TITLE
Images in subnamespace are not displayed: -usePictures and  -subns (fix presented)

### ISSUE THREAD

**Issue by rzagreb** [gturri/nspages#98]
**Problem**

When Using `-usePictures` and  `-subns` together, you will only see images for the current namespace but not for it's subnamespaces.

**Solution**

I was able to fix it by changing function `buildIdToLinkTo()` in  `dokuwiki/lib/plugins/nspages/fileHelper/namespacePreparer.php`. 

This is how it became

```php
    private function buildIdToLinkTo($idMainPage, $currentNsId){
        if(is_null($idMainPage)) {
            return $currentNsId . ':start';
        } else {
            return $idMainPage;
        }
    }
```
where 
```php
return $currentNsId . ':start';
``` 
it used to be
```php
return $currentNsId . ':';
``` 

Simple. Also, because it will render url `?id=<namespace>:start` instead of `?id=<namespace>:` in `<a>`.

**Comment by gturri** [comment]
Thank you for this bug report and for proposing a fix!

Unfortunately this patch would break some other usages. That's because the main page of a namespace isn't always `<namespace>:start`. There are at least two cases where a link  `?id=<namespace>:` isn't equivalent to `?id=<namespace>:start`:

* when the [start](https://www.dokuwiki.org/config:startpage) config of the wiki has been changed (in this case the equivalent link would be `?id=<namespace>:<config_for_start>`
* when there is a page called `<namespace>` and no page called `<start>` (that's the case in particular for the playground page: by default `?id=playground:` will result in a 302 which will redirect to `?id=playground:playground`)

AFAICS the proper way to fix it would be to find the function which translates a query to `?id=<namespace>:` and to call it here. (but that's just a guess since I haven't looked into in it)
